name: CI

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests successfully
        if: "! contains(toJSON(github.event.commits.*.message), 'fail')"
        run: exit 0
      - name: Run tests unsuccessfully
        if: "contains(toJSON(github.event.commits.*.message), 'fail')"
        run: exit 1
  stopwatch:
    environment: stopwatch
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Succeed!
        run: exit 0
